title: Geenoos
email: freiya1002@naver.com
description: 하루하루 공부한 거 끄적이기
author: Geenoos
baseurl: "/Geenoos.github.io"
url: "https://Geenoos.github.io"

# Social Profiles
twitter_username: None
github_username: Geenoos
facebook_username: 최진우
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
